// USER ACTION
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';
export const SHOW_USER_MODAL = 'SHOW_USER_MODAL';
export const HIDE_USER_MODAL = 'HIDE_USER_MODAL';
export const SHOW_REG_MODAL = 'SHOW_REG_MODAL';
export const HIDE_REG_MODAL = 'HIDE_REG_MODAL';
export const NEXT_REG_MODAL = 'NEXT_REG_MODAL';
export const BACK_REG_MODAL = 'BACK_REG_MODAL';
export const CLOSE_REG_MODAL = 'CLOSE_REG_MODAL';

export const USER_LOGIN_STATE = 'USER_LOGIN_STATE';
export const USER_LOGOUT_STATE = 'USER_LOGOUT_STATE';
export const SET_REG_STATE = 'SET_REG_STATE';

// DATA
export const SET_USER_BIRTHDAY = 'SET_USER_BIRTHDAY';